-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.players
(
    idplayer integer NOT NULL DEFAULT nextval('players_idplayer_seq'::regclass),
    name character varying(45) COLLATE pg_catalog."default" DEFAULT 'noData'::character varying,
    age integer DEFAULT 0,
    "position" character varying(100) COLLATE pg_catalog."default" DEFAULT 'noData'::character varying,
    college character varying(100) COLLATE pg_catalog."default" DEFAULT 'noData'::character varying,
    draftteam character varying(45) COLLATE pg_catalog."default" DEFAULT 'noData'::character varying,
    draftposition integer DEFAULT 0,
    draftyear integer DEFAULT 0,
    born date,
    experience integer DEFAULT 0,
    CONSTRAINT players_pkey PRIMARY KEY (idplayer)
);

CREATE TABLE IF NOT EXISTS public.playerseasons
(
    idplayer integer NOT NULL,
    idseason integer NOT NULL,
    idteam integer NOT NULL,
    age integer,
    league character varying(45) COLLATE pg_catalog."default",
    "position" character varying(45) COLLATE pg_catalog."default",
    games integer,
    gamesstarter integer,
    minutesplayed integer,
    fieldgoals integer,
    fgattempts integer,
    fgperc real,
    "3PTSFG" integer,
    "3PFGAttempts" integer,
    "3PFGPerc" real,
    "2PtsFG" integer,
    "2PFGAttempts" integer,
    "2PFGPerc" real,
    effectivegoalperc real,
    freethrows integer,
    freethrowsattempts integer,
    ftperc real,
    offrbds integer,
    defrbds integer,
    totalrbds integer,
    assists integer,
    steals integer,
    blocks integer,
    turnovers integer,
    fouls integer,
    points integer,
    tripledouble integer,
    CONSTRAINT playerseasons_pkey PRIMARY KEY (idplayer, idseason, idteam)
);

CREATE TABLE IF NOT EXISTS public.seasons
(
    idseason integer NOT NULL DEFAULT nextval('seasons_idseason_seq'::regclass),
    years character varying(45) COLLATE pg_catalog."default",
    league character varying(45) COLLATE pg_catalog."default",
    champion integer,
    mvp character varying(45) COLLATE pg_catalog."default",
    roty character varying(45) COLLATE pg_catalog."default",
    pointsleader character varying(45) COLLATE pg_catalog."default",
    reboundsleader character varying(45) COLLATE pg_catalog."default",
    assistsleader character varying(45) COLLATE pg_catalog."default",
    winsharesleader character varying(45) COLLATE pg_catalog."default",
    CONSTRAINT seasons_pkey PRIMARY KEY (idseason)
);

CREATE TABLE IF NOT EXISTS public.teams
(
    idteam integer NOT NULL DEFAULT nextval('teams_idteam_seq'::regclass),
    name character varying(45) COLLATE pg_catalog."default",
    location character varying(45) COLLATE pg_catalog."default",
    games integer,
    wins integer,
    loses integer,
    playoff integer,
    confchampions integer,
    nbachampions integer,
    conference character varying(45) COLLATE pg_catalog."default",
    CONSTRAINT teams_pkey PRIMARY KEY (idteam)
);

ALTER TABLE IF EXISTS public.playerseasons
    ADD CONSTRAINT playerseasons_idplayer_fkey FOREIGN KEY (idplayer)
    REFERENCES public.players (idplayer) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.playerseasons
    ADD CONSTRAINT playerseasons_idseason_fkey FOREIGN KEY (idseason)
    REFERENCES public.seasons (idseason) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.playerseasons
    ADD CONSTRAINT playerseasons_idteam_fkey FOREIGN KEY (idteam)
    REFERENCES public.teams (idteam) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.seasons
    ADD CONSTRAINT seasons_champion_fkey FOREIGN KEY (champion)
    REFERENCES public.teams (idteam) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

END;